apiVersion: v1
kind: PersistentVolume # PV is cluster-scoped
metadata:
  name: custom-jars-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany # allows a Persistent Volume (PV) to be mounted in read-write mode by multiple nodes simultaneously
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "custom-jars"
  local:
    path: /tmp/custom-jars2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - prod-test-worker2 # Match the node name in the Pod's nodeSelector: `kubectl get nodes --show-labels`
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: custom-jars-pvc
  namespace: spark-operator     # PV is namespace-scoped
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "custom-jars"
  resources:
    requests:
      storage: 1Gi