apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-wordcount
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: spark-wordcount:v2  # Your custom image
  imagePullPolicy: Never  # We will upload manually to the k8s workers
  mainClass: com.chen.guo.WordCountEMR
  mainApplicationFile: local:///opt/spark-work-dir/word-count.jar  # the Jar file need to be uploaded/mounted to this location
  arguments:
  - "file:///etc/passwd"
  sparkVersion: 4.0.0
  sparkConf:
    spark.kubernetes.executor.deleteOnTermination: "false"
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "file:///tmp/spark-events"
  driver:
    labels:
      version: 4.0.0
    env:
      - name: RUN_ID
        value: "1730936400"  # <-- we can patch a harmless change here to force kubectl resubmit
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
    securityContext:
      capabilities:
        drop:
        - ALL
      runAsGroup: 185
      runAsUser: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
    - name: spark-events
      mountPath: /tmp/spark-events
    initContainers:
    - name: create-event-log-dir
      image: busybox:1.36
      command: ['sh', '-c', 'mkdir -p /tmp/spark-events && chown -R 185:185 /tmp/spark-events && chmod 755 /tmp/spark-events']
      volumeMounts:
      - name: spark-events
        mountPath: /tmp/spark-events
  executor:
    labels:
      version: 4.0.0
    instances: 1
    cores: 1
    memory: 512m
    securityContext:
      capabilities:
        drop:
        - ALL
      runAsGroup: 185
      runAsUser: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
    - name: spark-events
      mountPath: /tmp/spark-events
    initContainers:
    - name: create-event-log-dir
      image: busybox:1.36
      command: ['sh', '-c', 'mkdir -p /tmp/spark-events && chown -R 185:185 /tmp/spark-events && chmod 755 /tmp/spark-events']
      volumeMounts:
      - name: spark-events
        mountPath: /tmp/spark-events
  volumes:
  - name: spark-events
    persistentVolumeClaim:
      claimName: spark-events-pvc  # This REFERENCES the existing PVC
