apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      serviceAccountName: jupyter-notebook
      containers:
        - name: jupyter
          image: jupyter/pyspark-notebook:latest
          ports:
            - containerPort: 8888
          env:
            - name: JUPYTER_ENABLE_LAB
              value: "yes"
            - name: GRANT_SUDO
              value: "yes"
          volumeMounts:
            - name: jupyter-data
              mountPath: /home/jovyan/work
      volumes:
        - name: jupyter-data
          persistentVolumeClaim:
            claimName: jupyter-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: jupyter-notebook
  ports:
    - port: 8888
      targetPort: 8888