apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyter-spark
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyter-spark-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyter-spark-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: jupyter-spark
    namespace: default
roleRef:
  kind: Role
  name: jupyter-spark-role
  apiGroup: rbac.authorization.k8s.io