apiVersion: v1
kind: Pod # a one-time, ad-hoc naked pod launched manually and NOT managed by a controller.
          # Most specs of the `POD` kind is immutable once the pod is created. Delete & recreate for updates.
metadata:
  name: custom-artifacts-pod
spec:
  restartPolicy: Never
  containers:
    - name: sh
      image: busybox:1.36
      command: ["sh","-c","sleep 86400000"]  # gives you 1000 days to upload the jars
      volumeMounts:
        - name: custom-artifacts
          mountPath: /custom-artifacts
  volumes:
    - name: custom-artifacts
      persistentVolumeClaim:
        # deploy this pod to the same worker as the driver
        claimName: custom-jars-pvc2
