package main

import (
	"fmt"
	"time"
)

func main() {
	stop := make(chan bool)

	go func() {
		for {
			select {
			//Limitation with this pattern: code will become complicated if
			// 1. Many routines to control
			// 2. Children routines generated by routines
			case <-stop:
				fmt.Println("Routine received exit signal. Exiting...")
				return
			default:
				fmt.Println("Work in progress in the routine...")
				time.Sleep(500 * time.Millisecond)
			}
		}
	}()

	time.Sleep(5 * time.Second)
	fmt.Println("Ready to exit routine")
	stop <- true

	time.Sleep(500 * time.Millisecond)
	fmt.Println("Done")
}
