apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: word-count-pvc
  namespace: default
spec:
  type: Java # both Java and Scala should work? to run an application from JAR
  mode: cluster
  image: docker.io/library/spark:4.0.0
  imagePullPolicy: IfNotPresent
  mainClass: com.chen.guo.WordCountEMR
  mainApplicationFile: local:///tmp/spark-jars/word-count.jar  # the Jar file need to be uploaded/mounted to this location
  arguments:
  - "file:///etc/passwd"
  sparkVersion: 4.0.0
  sparkConf:
    spark.kubernetes.executor.deleteOnTermination: "false"
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "file:///tmp/spark-events"
  driver:
    nodeSelector:
      kubernetes.io/hostname: prod-test-worker2 # Deploy to the same node as the SHS
    labels:
      version: 4.0.0
    env:
      - name: RUN_ID
        value: "1731936400"  # <-- we can patch a harmless change here to force kubectl resubmit
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
    securityContext: &security-context
      capabilities:
        drop:
        - ALL
      runAsGroup: 185
      runAsUser: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
    volumeMounts: &volume-mounts
    - name: spark-events
      mountPath: /tmp/spark-events
    - name: spark-jar
      mountPath: /tmp/spark-jars
    initContainers: &init-containers  # ← Define anchor here
    - name: create-event-log-dir
      image: busybox:1.36
      command:
        - 'sh'
        - '-c'
        - |
          mkdir -p /tmp/spark-events /tmp/spark-jars
          chown -R 185:185 /tmp/spark-events /tmp/spark-jars
          chmod 755 /tmp/spark-events /tmp/spark-jars
      volumeMounts:
      - name: spark-events
        mountPath: /tmp/spark-events
      - name: spark-jar
        mountPath: /tmp/spark-jars
  executor:
    labels:
      version: 4.0.0
    instances: 1
    cores: 1
    memory: 512m
    securityContext: *security-context
    volumeMounts: *volume-mounts
    initContainers: *init-containers  # ← Reference anchor here
  volumes:
  - name: spark-events
    persistentVolumeClaim:
      claimName: spark-events-pvc
  - name: spark-jar
    persistentVolumeClaim:
      claimName: custom-jars-pvc2
