apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      labels:
        app: spark-history-server
    spec:
      # Need to deploy on the same node as the Spark driver which writes the events to the PVC
      nodeSelector:
        kubernetes.io/hostname: prod-test-worker
      containers:
      - name: spark-history-server
        image: docker.io/library/spark:4.0.0
        command: ["/opt/spark/sbin/start-history-server.sh"]
        env:
        - name: SPARK_NO_DAEMONIZE
          value: "true"
        - name: SPARK_HISTORY_OPTS
          value: "-Dspark.history.fs.logDirectory=file:///tmp/spark-events"
        ports:
        - containerPort: 18080
          name: http
        volumeMounts:
        - name: spark-events
          mountPath: /tmp/spark-events
      volumes:
      - name: spark-events
        persistentVolumeClaim:
          claimName: spark-events-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 18080
    targetPort: 18080
    name: http
  selector:
    app: spark-history-server